import keycloak
from secret import kc_admin_secrets

class KcAdministrator:
    """
    This class is used to build, delete and logout test users on the Keycloak
    instance for my bachelor thesis

    :param printer: A function that can print text to the console. Defaults to
        print

    :param printer_args: Positional Arguments for the supplied printing func
        tion
    
    :param printer_kwargs: Keyword Arguments for the supplied printing func
        tion
    """
    def __init__(
            self,
            printer = print,
            printer_args = [],
            printer_kwargs = {}
            ):
        """
        Instantiates a KcAdministrator
        """
        self._kc_admin = keycloak.KeycloakAdmin(
            server_url = kc_admin_secrets.KEYCLOAK_URL,
            username = kc_admin_secrets.KEYCLOAK_ADMIN_USERNAME,
            password = kc_admin_secrets.KEYCLOAK_ADMIN_PASSWORD,
            realm_name = kc_admin_secrets.KEYCLOAK_REALM,
            user_realm_name = kc_admin_secrets.KEYCLOAK_USER_REALM
        )
        self.printer = printer
        self.printer_args = printer_args
        self.printer_kwargs = printer_kwargs


    def build_uid_to_uname_lookup_dict(self, user_list):
        """
        Generates a dictionary, which has User-IDs as keys and usernames as
        values. Each User-ID has their respective username as a value. To get
        an ID from a username, use get_uid_from_uname()

        :param user_list: A list of UserRepresentations (See https://www.key
            cloak.org/docs-api/latest/rest-api/index.html#UserRepresentation)
            for more information on how a UserRepresentation can look like)

        :return: A dictionary containing pairs of User-ID and username, with
            the keys being the User-ID and the values being their respective
            username
        """
        lookup = {}

        # user was originally user_representation as this was a more accurate
        # name. It was changed because it was too long.
        for user in user_list:
            lookup[user["id"]] = user["username"]
        
        
        return lookup


    def fetch_uids_from_user_list(self, user_list):
        """
        Fetches the User-ID for each UserRepresentation in the user_list

        :param user_list: A list of UserRepresentations (See https://www.key
            cloak.org/docs-api/latest/rest-api/index.html#UserRepresentation)
            for more information on how a UserRepresentation can look like)
        
        :return: A list containing all User-IDs contained inside the UserRe-
            presentations of the user_list
        """
        return [
            user_representation["id"] for user_representation in user_list
            ]


    def get_user_list(self, username = "t_user_"):
        """
        Gets a list of UserRepresentations from the Keycloak instance

        :param username: Filter for the API-Call. Only UserRepresentations con
            taining the supplied username somewhere inside its username field
            are returned. Defaults to "t_user_"
        
        :return: A list of UserRepresentations, including only those that con
            tain the supplied username somewhere inside their username field
        """
        return self._kc_admin.get_users(
            query = {"username": username}
            )
    

    def _is_user_locally_known(self, username):
        """
        Private function that checks if the username is a key in the TEST_USER
        _PASSWORDS dict

        :param username: The username to look up in the passwords dictionary

        :return: True, if the user is a key in the dictionary. False otherwise
        """
        return username in kc_admin_secrets.TEST_USER_PASSWORDS

        
    def get_uid_from_uname(self, username, uid_to_uname_lookup):
        """
        Uses a User-ID to username lookup dictionary to extract the User-ID
        associated with the username

        :param username: The username of the user, whose ID is to be looked up

        :param uid_to_uname_lookup: A dictionary generated by build_uid_to_
            uname_lookup_dict(user_list) which contains User-IDs as keys and
            usernames as values
        
        :return: The User-ID for the username, if it is contained in the dict
            tionary. Otherwise returns None.
        """
        if username in uid_to_uname_lookup.values():
            return list(uid_to_uname_lookup.keys())[
                list(uid_to_uname_lookup.values()).index(username)
                ]
        else:
            return None 


    def get_test_user_password(self, username = None):
        """
        Fetches the password for the given test user

        :param username: The username of the test user, whose password is to
            be returned
        
        :return: The password for the given user. Returns None if the user
            doesn't exist or if the user doesn't have a locally known password
        """

        user_list = self.get_user_list()
        uid_to_uname_lookup = self.build_uid_to_uname_lookup_dict(user_list)

        if not username:
            return None
        
        # Checks if the username exists.
        user_id = self.get_uid_from_uname(username, uid_to_uname_lookup)
        if not user_id:
            return None
        
        # Checks if the password for the username is known.
        if not self._is_user_locally_known(username):
            return None

        return kc_admin_secrets.TEST_USER_PASSWORDS[username]


    def _print_user_list(self, username = "t_user"):
        """
        Private debug function, that prints out the contents of the user list
        of the Keycloak Instance

        :param username: Filter for get_user_list. get_user_list only returns
            UserRepresentations containing the supplied username somewhere in
            side its username field. Defaults to "t_user"
        """
        user_list = self.get_user_list(username)
        self.printer(user_list, *self.printer_args, **self.printer_kwargs)


    def _print_sessions(self, user_ids):
        """
        Private debug function, that prints out all the currently active ses
        sions for all supplied User-IDs

        :param user_ids: A list containing the User-IDs, whose active session
            are to be checked
        """
        sessions = {}
        for user_id in user_ids:
            sessions[user_id] = self._kc_admin.get_sessions(user_id)
        self.printer(sessions)


    def create_test_users(self):
        """
        Creates 1000 test users for the Keycloak instance
        """
        # For more information on UserRepresentation or CredentialRepresenta-
        # tion see the following links:
        # TODO: Input links
        user_representation_base = {
            "username": "",
            "enabled": True,
            "credentials": [
                {
                    "userLabel": "Password",
                    "temporary": False,
                    "type": "password",
                    "value": ""
                }
            ]
        }

        for i in range(1, 1001):
            # Using .copy() here is important, as dictionaries, as well as
            # lists, are copied by reference. a = {"a": 1}, b = a and then
            # b["a"] = 2 would lead to "a" being set to 2 in a too.
            new_user = user_representation_base.copy()
            new_user["username"] = f"t_user_{i}"
            new_user["credentials"][0]["value"] = \
                kc_admin_secrets.TEST_USER_PASSWORDS[f"t_user_{i}"]
            self._kc_admin.create_user(new_user)
        

    def delete_test_users(self):
        """
        Deletes the 1000 test users
        """
        keycloak_admin = self._kc_admin
        user_list = self.get_user_list()
        user_ids = self.fetch_uids_from_user_list(user_list)

        for user_id in user_ids:
            keycloak_admin.delete_user(user_id)


    def logout_all_kc_sessions(self, number_of_users_to_logout = None):
        """
        Clears all active sessions for all test users. Optionally only logs
        out only the specified number of users.

        :param number_of_users_to_logout: Optional The number of users to log
            out. Defaults to None, which logs out all 1000 users.
        """
        user_list = self.get_user_list()
        #self.printer(user_list, *self.printer_args, **self.printer_kwargs)

        # Only really important for debugging / logging purposes.
        #uid_to_uname_lookup = self.build_uid_to_uname_lookup_dict(user_list)
        #self.printer(uid_to_uname_lookup)

        # In order to clear all sessions we need to first get all uids from
        # the user_list.
        user_ids = self.fetch_uids_from_user_list(user_list)
        #self.printer(user_ids, *self.printer_args, **self.printer_kwargs)
        if number_of_users_to_logout:
            user_ids = user_ids[:number_of_users_to_logout]

        # Clears all sessions of all known users of the current realm.
        for user_id in user_ids:
            self._kc_admin.user_logout(user_id)
